### ISSUE TITLE
Wrong and missing braille shortcut for Freedom Scientific

### ISSUE THREAD

**Issue by daniel-1964** [Andre9642/BrailleExtender#25]
I have noticed tow errors in the Freedom Scientific profile:
1) The shortcut BrailleSpace+dot1+dot4+dot5+dot8 for "gethelp" hides the shortcut for f4. I suggest to remove it because gethelp has the shortcut BrailleSpace+dot1+dot2+dot5
2) The shortcut for autotest is wrong. It was braillespacebar+dot2+dot3+dot4+dot5+dot7+b8 instead of braillespacebar+dot2+dot3+dot4+dot5+dot7+dot8
3) Unable to apply modifier keys to some arrow keys, insert delete. For example I can't do BrailleSpace+dot1+dot4 followed by BrailleSpace+dot6 to obtain control-right-arrow. No mean to enter control-delete. Something like BrailleSpace+dot1+dot4 followed by BrailleSpace+dot1+dot4+dot5 should be fine as I do for Control-F4 by example.

**Comment by daniel-1964** [comment]
Hi,
firstly, sorry for the delay.

I've juste tested the latest dev version of the addon, and no changes has been constated from my previous tests.

I attach my nvda-log and my gesture.ini if that can help.

My test are:
1) With the nvda keyhelp function (nvda+1) I hit ctrl-up, ctrl-down, ctrl-left, ctrl-right, ctrl-home, ctrl-end, up, down, left, right, home, end; except for ctrl-up and ctll-down, all ctll-x keys does not work.
2) I hit ctrl-f1 through ctrl-f12, f1 though f12; only f1...f12 works.
3. I open notepad and I did the same previous two test. I got the same results.

HTH and let me know how I can help.

[nvda-old.log](https://github.com/Andre9642/BrailleExtender/files/2447317/nvda-old.log)
[gestures.ini.txt](https://github.com/Andre9642/BrailleExtender/files/2447335/gestures.ini.txt)

**Comment by Andre9642** [comment]
Thanks for your feedback and no problem for the delay! :)
Could you try with the latest version please? Is it better for you?
Thanks

**Comment by daniel-1964** [comment]
Hi, 
Think for tbis improvement, it is fine for me.
As you say some work is needed (i.e. for shift and windows key), but it's better for me.
My quick tests show that nvda work in all cases, ctrl and alt work. The combination ctrl+alt doesn't.
HTH, I can make other tests if you need.

**Comment by daniel-1964** [comment]
Good job!

Still does not work shift modifier + arrows/function keys.
Inside the nvda key-helper nvda+1, I can not exit with the nvda modifier + 1. Other nvda modifier combination seems to work.

**Comment by charadani** [comment]
Thanks for this awsome work.
A couple more suggestions concerning the Freedom Scientific layout.
* the default NVDA configuration has BrailleSpaceBar+Dot4+Dot5 for Tab and BrailleSpaceBar=Dot1+dot2 for Shift+Tab. I don't really think you should override these gestures since they are aligned with some other use cases of the Freedom Scientific braille displays for some other screen readers. Currently the Tab gesture works but the Shift+Tab one is binded to the battery information.
* The following four gestures I think should be implemented since they are much more used than the ones that are currently binded to the gestures:
  * BrailleSpaceBar+Dot2, currently binded to Home, should be binded to CRTL+Left arrow
  * BrailleSpaceBar+Dot5, currently binded to End, should be binded to CRTL+Right arrow
  * BrailleSpaceBar+dot1+dot3, currently binded to PageUp, should be binded to Home.
  * BrailleSpaceBar+Dot4+dot6, currently binded to PageDown, should be binded to End.
This is based on my use of the Focus Braille Display with NVDA without this extension and for consistency with JAWS mainly. In general, we should stick as much as possible to the original gestures and to those gestures people is more used to. Of course this is personal preference.

**Comment by Andre9642** [comment]
@charadani Thanks! Completely agree with you. Unfortunately I don't have this braille display, so I count on contributions to improve this! Also the profile editor feature (for gestures map) must be continued in order to facilitate this.
Feel free to make a PR if you want. Otherwise I'll fix this from July.

**Comment by Andre9642** [comment]
@charadani could you try the latest dev version please? Thanks and sorry for the delay.

**Comment by charadani** [comment]
I will try and let you know. Thanks a lot!

**Comment by daniel-1964** [comment]
Hi,

I've just tried the latest release and see a mistake,
in file freedomscientific/default/gestures.ini:
1) replace lines 27 and 28 by the two following:
	kb:control+leftArrow = br(freedomscientific):braillespacebar+dot2, br(freedomscientific):braillespacebar+dot3+dot6+dot7
	kb:control+rightArrow = br(freedomscientific):braillespacebar+dot5, br(freedomscientific):braillespacebar+dot3+dot6+dot8

2) Remove lines 46 and 47

Witout this modifications, the extended refuses to load because of duplicate keys in gesture.ini

HTH.

Daniel

**Comment by daniel-1964** [comment]
Another suggestion,
I just releazed that we lost a shortcut for pageup and pagedown:
I suggest 
	kb:pageup = br(freedomscientific):braillespacebar+dot1+dot2+dot3+dot7
	kb:pagedown = br(freedomscientific):braillespacebar+dot4+dot5+dot6+dot8

I forget the shortcut usesd by Jaws, but if you can get them and apply them without disturbing the other brailleextender shurtcuts, it's a good idea to use jaws's ones.

HTH,
Daniel

**Comment by Andre9642** [comment]
@daniel-1964 Thanks! Done.
I have set your name and email adress as the author of these commits. The same that your other contributions.
Unfortunately, the e-mail address daniel@gmail.com is attached to skrdaniel github account (not to @daniel-1964).
Is there an error in your git settings?
What email address should be used for your contributions?

**Comment by daniel-1964** [comment]
It's my true email but I down know why github use skrdaniel instead of daniel-1964???
It's now so important I beleive...
